version: '3.8'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: my_api_rest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./SQLtable.sql:/docker-entrypoint-initdb.d/SQLtable.sql
    networks:
      - postgres-network

  redis:
    image: redis:latest
    volumes:
      - redis-data:/data
    networks:
      - redis-network

  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_DB: my_api_rest
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
    depends_on:
      - postgres
      - redis
    networks:
      - redis-network
      - postgres-network

networks:
  redis-network:
    driver: bridge
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
